### PR TITLE
percona-server57 and keg only copies for multi version installs

### PR DESCRIPTION
**Pull request by bbergstrom**
## Description
* Created percona-server57 with https://github.com/Homebrew/homebrew/blob/65ff734263e0599fc6f194a22162d4b6b1cba395/Library/Formula/percona-server.rb as a base.  Modified it to use latest stable version.
* Created percona-server55-keg-only as a keg only copy of percona-server55 for multi version installs.  Modified to use versioned data directory and not conflict with other percona-server formulas..
* Created percona-server57-keg-only as a keg only copy of percona-server57 for multi version installs.  Modified to use versioned data directory and not conflict with other percona-server formulas.
* Removed our outdated custom version of percona-server55 in favor of better and updated homebrew versions one.

Is easier to see changes by reviewing all commits after the first.

For reference: http://www.rubydoc.info/github/Homebrew/homebrew/master/Formula#keg_only-class_method

## QA
Note, it _shouldn't_ happen, but this has the risk of losing your existing mysql data directory.

### Prep
```
mysql.server stop
brew tap --full sportngin/homebrew
cd /usr/local/Library/Taps/sportngin/homebrew-homebrew/
git pull
git checkout percona57
```
### Tests
```
brew install percona-server55 && brew install percona-server57 # should stop due to conflict
brew uninstall percona-server55 && brew install percona-server57  # Linked 5.7 install
brew install percona-server55-keg-only  # Keg only 5.5 with linked 5.7
brew install percona-server55 # should stop due to conflict
brew uninstall percona-server57 && brew uninstall percona-server57-keg-only && brew install  percona-server55  # Linked 5.5 install
brew install percona-server57-keg-only  # Keg only 5.7 with linked 5.5
```

### Reset
```
brew uninstall percona-server57-keg-only
cd /usr/local/Library/Taps/sportngin/homebrew-homebrew/
git checkout master
mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix percona-server55)" --datadir=/usr/local/var/mysql --tmpdir=/tmp
mysql.server start
```

### CODE REVIEW

**Comment by anfleene** [comment]
installing 57 then 55 doesn't seem to conflict.

**Comment by anfleene** [comment]
Well it does once it tries to link it.

**Comment by bbergstrom** [comment]
@anfleene With the deletion of our percona-server55 forumla, its now resolving to https://github.com/Homebrew/homebrew-versions/blob/master/percona-server55.rb which doesn't know about ours.  Do you think its worth forking that formula to make the conflict list accurate?

**Comment by anfleene** [comment]
meh. I think it's fine.

**Pull request merged**
